# Generated by Django 3.2.6 on 2021-08-21 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_bg_image', models.ImageField(upload_to='about_images', verbose_name='Set home Background Image')),
                ('about_img', models.ImageField(upload_to='about_images', verbose_name='Set about section image')),
                ('about_details', models.TextField(verbose_name='Write Details about you')),
                ('happy_client', models.IntegerField(default=0)),
                ('year_of_experience', models.IntegerField(default=0)),
                ('number_of_projects', models.IntegerField(default=0)),
                ('number_of_awards', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='client_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=128)),
                ('message', models.TextField()),
                ('send_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Client Message Section',
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkdin_url', models.URLField(blank=True, null=True)),
                ('Email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'verbose_name_plural': 'contact section',
            },
        ),
        migrations.CreateModel(
            name='portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('project_image', models.ImageField(upload_to='project_image')),
                ('project_name', models.CharField(max_length=128)),
                ('project_details', models.TextField()),
                ('project_url', models.URLField(blank=True, null=True)),
                ('project_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'portfolio Section',
            },
        ),
        migrations.CreateModel(
            name='services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=256)),
                ('service_text', models.CharField(max_length=512)),
            ],
            options={
                'verbose_name_plural': 'Service Section',
            },
        ),
        migrations.CreateModel(
            name='testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=64)),
                ('client_title', models.CharField(blank=True, max_length=128, null=True)),
                ('client_image', models.ImageField(blank=True, null=True, upload_to='client_images')),
                ('client_comment', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'testimonial section',
            },
        ),
    ]
