# Generated by Django 3.2.6 on 2021-08-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20210822_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Portfolio Category',
            },
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio_category'),
        ),
    ]
