# Generated by Django 3.2.6 on 2021-08-26 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210823_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('skill_value', models.PositiveIntegerField(default=0, help_text='set your skill value out of 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
            options={
                'verbose_name_plural': 'Skills Section',
            },
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('-id',), 'verbose_name_plural': 'Portfolio Section'},
        ),
    ]
