# Generated by Django 3.2.6 on 2021-08-27 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20210827_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='set your resume title - like as Education , Professional Experience', max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Resume Category',
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('duration', models.CharField(max_length=20)),
                ('location', models.CharField(help_text='Set your institue or workspace name and location', max_length=250)),
                ('details', models.TextField(help_text='Set your position Details')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.resume_category')),
            ],
            options={
                'verbose_name_plural': 'Resume Section',
            },
        ),
    ]
