# Generated by Django 3.2.6 on 2021-08-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_resume_resume_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='Cv',
            field=models.FileField(blank=True, null=True, upload_to='self_cv', verbose_name='Upload Your CV'),
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(blank=True, help_text='set your self-titles separated by comma and single whitespace ,likes Designer, Developer, bla, bla ', max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='duration',
            field=models.CharField(help_text='set working durations like as , 2017 - 2020 or now', max_length=20),
        ),
    ]
