# Generated by Django 3.2.6 on 2021-08-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20210827_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_img',
            field=models.ImageField(default='sajjad_.jpg', upload_to='about_images', verbose_name='Set about section image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='home_bg_image',
            field=models.ImageField(default='Image_HD.png', upload_to='about_images', verbose_name='Set home Background Image'),
        ),
    ]
