# Generated by Django 3.2.6 on 2021-08-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20210828_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_img',
            field=models.ImageField(default='sajjad__KXX4lTn.jpg', upload_to='about_images', verbose_name='Set about section image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='home_bg_image',
            field=models.ImageField(default='Image_HD_yxHFs25.png', upload_to='about_images', verbose_name='Set home Background Image'),
        ),
    ]
