# Generated by Django 3.2.6 on 2021-08-31 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_auto_20210829_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about_img',
            field=models.ImageField(upload_to='about_images', verbose_name='Set about section image'),
        ),
        migrations.AlterField(
            model_name='about',
            name='home_bg_image',
            field=models.ImageField(upload_to='about_images', verbose_name='Set home Background Image'),
        ),
    ]
